USE CHUYEN_HANG_ONLINE
GO
CREATE TABLE DOI_TAC
(
	MA_DT CHAR(8) NOT NULL,

	TEN_DT NVARCHAR(20),
	NGUOI_DAI_DIEN NVARCHAR(30),
	THANH_PHO NVARCHAR(15),
	QUAN NVARCHAR(15),
	DIA_CHI_KINH_DOANH NVARCHAR(30),
	SO_CHI_NHANH INT,
	LOAI_HANG NVARCHAR(20),
	SO_DT VARCHAR(10),
	EMAIL VARCHAR(30),

	PRIMARY KEY (MA_DT)
)
GO

ALTER TABLE DOI_TAC ALTER COLUMN SO_CHI_NHANH INT
GO

CREATE TABLE HOP_DONG
(
	MA_HD VARCHAR(10),

	MA_THUE_DT VARCHAR(15),
	NGUOI_DAI_DIEN NVARCHAR(30),
	MA_CN_DK VARCHAR(8),
	DIA_CHI_CAC_CN NVARCHAR(30),
	NGAY_BD DATE,
	NGAY_KT DATE,
	MA_DT CHAR(8),

	PRIMARY KEY (MA_HD)
)
GO

CREATE TABLE CHI_NHANH
(
	MA_CN VARCHAR(8) NOT NULL,

	MA_DT CHAR(8), 
	DIA_CHI_CN NVARCHAR(30),

	PRIMARY KEY (MA_CN)
)

CREATE TABLE SAN_PHAM
(
	MA_SP VARCHAR(8) NOT NULL,

	MA_CN VARCHAR(8),
	TEN_SP NVARCHAR(20),
	MO_TA NVARCHAR(30),
	GIA_SP INT,

	PRIMARY KEY (MA_SP)
)

ALTER TABLE HOP_DONG ADD CONSTRAINT FK_HOP_DONG_DOI_TAC FOREIGN KEY(MA_DT) REFERENCES DOI_TAC(MA_DT)
GO
ALTER TABLE CHI_NHANH ADD CONSTRAINT FK_CN_DT FOREIGN KEY(MA_DT) REFERENCES DOI_TAC(MA_DT)
GO
ALTER TABLE HOP_DONG ADD CONSTRAINT FK_HD_CN FOREIGN KEY(MA_CN_DK) REFERENCES CHI_NHANH(MA_CN)
GO
ALTER TABLE SAN_PHAM ADD CONSTRAINT FK_SP_CN FOREIGN KEY(MA_CN) REFERENCES CHI_NHANH(MA_CN)
GO

EXEC SP_ADDLOGIN 'DOITAC1','DOITAC1','CHUYEN_HANG_ONLINE'
GO
CREATE USER DOITAC1 FOR LOGIN DOITAC1
GO
EXEC SP_ADDROLE 'DOITAC'
GO
EXEC SP_ADDROLEMEMBER 'DOITAC','DOITAC1'
GO
GRANT SELECT, INSERT, UPDATE, DELETE ON SAN_PHAM TO DOITAC
GRANT SELECT, INSERT, UPDATE, DELETE ON CHI_NHANH TO DOITAC


USE CHUYEN_HANG_ONLINE
GO
CREATE TABLE KHACH_HANG
(
	MA_KH CHAR(8) NOT NULL,

	HO_TEN NVARCHAR(30),
	DIA_CHI NVARCHAR(30),
	SO_DT VARCHAR(10),
	EMAIL VARCHAR(30),

	PRIMARY KEY (MA_KH)
)
GO
CREATE TABLE DON_HANG
(
	MA_DH VARCHAR(8) ,

	MA_SP VARCHAR(8),
	MA_DT CHAR(8),
	MA_KH CHAR(8),
	SO_LUONG INT,
	HINH_THUC_TT NVARCHAR(30),
	DIA_CHI_GH	NVARCHAR(30),
	TINH_TRANG NVARCHAR(35),
	PHI_SP INT,
	PHI_VC INT,
	PRIMARY KEY (MA_DH)
)
GO
CREATE TABLE TAI_XE
(
	MA_TX CHAR(8),

	HO_TEN NVARCHAR(30),
	CMND  CHAR(10),
	SO_DT VARCHAR(10),
	BIEN_SO CHAR(15),
	KHU_VUC_HD NVARCHAR(20),
	EMAIL VARCHAR(30),
	TAI_KHOAN_NH CHAR(20),
	PRIMARY KEY (MA_TX)
)
ALTER TABLE DON_HANG ADD CONSTRAINT FK_DH_DT FOREIGN KEY(MA_DT) REFERENCES DOI_TAC(MA_DT)
GO
ALTER TABLE DON_HANG ADD CONSTRAINT FK_DH_SP FOREIGN KEY(MA_SP) REFERENCES SAN_PHAM(MA_SP)
GO
ALTER TABLE DON_HANG ADD CONSTRAINT FK_DH_KH FOREIGN KEY(MA_KH) REFERENCES KHACH_HANG(MA_KH)

EXEC SP_ADDLOGIN 'KHACHHANG1','KHACHHANG1','CHUYEN_HANG_ONLINE'
GO
CREATE USER KHACHHANG1 FOR LOGIN KHACHHANG1
GO
EXEC SP_ADDROLE 'KHACHHANG'
GO
EXEC SP_ADDROLEMEMBER 'KHACHHANG','KHACHHANG1'
GO
GRANT INSERT ON KHACH_HANG TO KHACHHANG
GRANT SELECT, INSERT ON DON_HANG TO KHACHHANG
GRANT SELECT ON SAN_PHAM TO KHACHHANG
GRANT SELECT ON DOI_TAC TO KHACHHANG


EXEC SP_ADDLOGIN 'TAIXE1','TAIXE1','CHUYEN_HANG_ONLINE'
GO
CREATE USER TAIXE1 FOR LOGIN TAIXE1
GO
EXEC SP_ADDROLE 'TAIXE'
GO
EXEC SP_ADDROLEMEMBER 'TAIXE','TAIXE1'
GO
GRANT INSERT  ON TAI_XE TO TAIXE
GRANT SELECT, UPDATE ON DON_HANG TO TAIXE
