USE CHUYEN_HANG_ONLINE;

--Cấp quyền cho tài khoản đăng nhập
GO
EXEC SP_ADDLOGIN 'DANGNHAP','DANGNHAP','CHUYEN_HANG_ONLINE';
CREATE USER DANGNHAP FOR LOGIN DANGNHAP;
GRANT SELECT ON TAI_KHOAN TO DANGNHAP;
GRANT SELECT ON DOI_TAC TO DANGNHAP;
GRANT SELECT ON KHACH_HANG TO DANGNHAP;
GRANT SELECT ON TAI_XE TO DANGNHAP;
GRANT EXECUTE ON OBJECT::dbo.dang_nhap TO DANGNHAP;

--Cấp quyền cho role đối tác
GO
EXEC SP_ADDLOGIN 'DOITAC1','DOITAC1','CHUYEN_HANG_ONLINE';
CREATE USER DOITAC1 FOR LOGIN DOITAC1;
EXEC SP_ADDROLE 'DOITAC';
EXEC SP_ADDROLEMEMBER 'DOITAC','DOITAC1';
GRANT SELECT, INSERT, UPDATE, DELETE ON SAN_PHAM TO DOITAC;
GRANT SELECT, INSERT, UPDATE, DELETE ON CHI_NHANH_SP TO DOITAC;
GRANT SELECT, INSERT, UPDATE ON HOP_DONG TO DOITAC;
GRANT SELECT, UPDATE ON DON_HANG TO DOITAC;
GRANT SELECT, UPDATE ON DOI_TAC TO DOITAC;
GRANT SELECT, UPDATE ON CHI_NHANH TO DOITAC;
GRANT EXECUTE ON dbo.chi_nhanh_chua_ki_hd TO DOITAC
GRANT EXECUTE ON dbo.gia_han_hop_dong_ERROR TO DOITAC
GRANT EXECUTE ON dbo.gia_han_hop_dong TO DOITAC
GRANT EXECUTE ON dbo.cap_nhat_san_pham TO DOITAC
GRANT EXECUTE ON dbo.cap_nhat_so_luong_cnsp_ERROR TO DOITAC
GRANT EXECUTE ON dbo.cap_nhat_so_luong_cnsp TO DOITAC
GRANT EXECUTE ON dbo.doi_tac_thong_ke_ERROR TO DOITAC
GRANT EXECUTE ON dbo.doi_tac_thong_ke TO DOITAC

--Cấp quyền khách hàng
GO
EXEC SP_ADDLOGIN 'KHACHHANG1','KHACHHANG1','CHUYEN_HANG_ONLINE';
CREATE USER KHACHHANG1 FOR LOGIN KHACHHANG1;
EXEC SP_ADDROLE 'KHACHHANG';
EXEC SP_ADDROLEMEMBER 'KHACHHANG','KHACHHANG1';
GRANT SELECT ON DOI_TAC TO KHACHHANG;
GRANT SELECT ON CHI_NHANH TO KHACHHANG;
GRANT SELECT ON SAN_PHAM TO KHACHHANG;
GRANT SELECT ON CHI_NHANH_SP TO KHACHHANG;
GRANT SELECT, INSERT ON DON_HANG TO KHACHHANG;
GRANT SELECT, INSERT ON DON_HANG_SP TO KHACHHANG;
GRANT EXECUTE ON TYPE::SAN_PHAM_SO_LUONG TO KHACHHANG;
GRANT SELECT, UPDATE ON KHACH_HANG TO KHACHHANG;
GRANT EXECUTE ON dbo.khach_hang_thong_ke_ERROR TO KHACHHANG
GRANT EXECUTE ON dbo.khach_hang_thong_ke TO KHACHHANG
GRANT EXECUTE ON dbo.tao_don_dat_hang_ERROR TO KHACHHANG
GRANT EXECUTE ON dbo.khach_hang_thong_ke TO KHACHHANG
GRANT EXECUTE ON dbo.huy_don_dat_hang_ERROR TO KHACHHANG
GRANT EXECUTE ON dbo.huy_don_dat_hang TO KHACHHANG

--Cấp quyền tài xế
GO
EXEC SP_ADDLOGIN 'TAIXE1','TAIXE1','CHUYEN_HANG_ONLINE';
CREATE USER TAIXE1 FOR LOGIN TAIXE1;
EXEC SP_ADDROLE 'TAIXE';
EXEC SP_ADDROLEMEMBER 'TAIXE','TAIXE1';
GRANT SELECT, UPDATE ON TAI_XE TO TAIXE;
GRANT SELECT, UPDATE ON DON_HANG TO TAIXE;
GRANT EXECUTE ON dbo.tai_xe_thong_ke_ERROR TO TAIXE
GRANT EXECUTE ON dbo.tai_xe_thong_ke TO TAIXE
GRANT EXECUTE ON dbo.tiep_nhan_dh_ERROR TO TAIXE
GRANT EXECUTE ON dbo.tiep_nhan_dh TO TAIXE


--Cấp quyền cho nhân viên
GO
EXEC SP_ADDLOGIN 'NHANVIEN1','NHANVIEN1','CHUYEN_HANG_ONLINE';
CREATE USER NHANVIEN1 FOR LOGIN NHANVIEN1;
EXEC SP_ADDROLE 'NHANVIEN';
EXEC SP_ADDROLEMEMBER 'NHANVIEN','NHANVIEN1';
GRANT SELECT ON DOI_TAC TO NHANVIEN;
GRANT SELECT, UPDATE ON HOP_DONG TO NHANVIEN;



--Cấp quyền cho quản trị viên
--QTV: quản trị viên
EXEC SP_ADDLOGIN 'QTV1','QTV1','CHUYEN_HANG_ONLINE';
CREATE USER QTV1 FOR LOGIN QTV1;
ALTER ROLE db_datareader
	ADD MEMBER QTV1;
ALTER ROLE db_datawriter
	ADD MEMBER QTV1;

